### ISSUE TITLE
Can't find the images after I run scraper

### ISSUE THREAD

**Issue by yuanchang200** [firmadyne/scraper#11]
Hi, after I run "scrapy crawl dlink", the "output" directory is created but there is no downloaded image files in it, and I can't find them  anywhere. The output of this command is something like this:

2017-11-18 21:46:24 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=NWD-370N&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:25 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=ZyWALL%201050&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:26 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=PLA-470&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:26 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=SFP-1000T&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=XGS3600-28F&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:27 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2016, 3, 3, 0, 0),
 'mib': u'ftp://ftp2.zyxel.com/XGS3600-28F/mib_file/XGS3600-28F_1.mib',
 'product': u'XGS3600-28F',
 'url': u'ftp://ftp2.zyxel.com/XGS3600-28F/firmware/XGS3600-28F_V1.00(AAFM.2)C0.zip',
 'vendor': 'zyxel',
 'version': u'V1.00(AAFM.2)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:27 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2015, 10, 12, 0, 0),
 'mib': u'ftp://ftp2.zyxel.com/XGS3600-28F/mib_file/XGS3600-28F_1.mib',
 'product': u'XGS3600-28F',
 'url': u'ftp://ftp2.zyxel.com/XGS3600-28F/firmware/XGS3600-28F_1.00(AAFM.0)C0.zip',
 'vendor': 'zyxel',
 'version': u'1.00(AAFM.0)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=P-660HW-61&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:27 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2006, 11, 10, 0, 0),
 'product': u'P-660HW-61',
 'url': u'ftp://ftp2.zyxel.com/P-660HW-61/firmware/P-660HW-61_3.40(PE.11)C0.zip',
 'vendor': 'zyxel',
 'version': u'3.40(PE.11)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:27 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2006, 11, 10, 0, 0),
 'product': u'P-660HW-61',
 'url': u'ftp://ftp2.zyxel.com/P-660HW-61/firmware/P-660HW-61_3.40(PE.11)C0.zip',
 'vendor': 'zyxel',
 'version': u'3.40(PE.11)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:28 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2005, 11, 7, 0, 0),
 'product': u'P-660HW-61',
 'url': u'ftp://ftp2.zyxel.com/P-660HW-61/firmware/P-660HW-61_3.40(PE.10)C0.zip',
 'vendor': 'zyxel',
 'version': u'3.40(PE.10)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=MC100FX-SC30-A&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:29 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=NAS520&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:29 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2017, 6, 9, 0, 0),
 'product': u'NAS520',
 'url': u'ftp://ftp2.zyxel.com/NAS520/firmware/NAS520_V5.21(AASZ.0)C0.zip',
 'vendor': 'zyxel',
 'version': u'V5.21(AASZ.0)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:29 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2016, 10, 19, 0, 0),
 'product': u'NAS520',
 'url': u'ftp://ftp2.zyxel.com/NAS520/firmware/NAS520_V5.20(AASZ.0)C0.zip',
 'vendor': 'zyxel',
 'version': u'V5.20(AASZ.0)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:29 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2016, 6, 27, 0, 0),
 'product': u'NAS520',
 'url': u'ftp://ftp2.zyxel.com/NAS520/firmware/NAS520_V5.11(AASZ.3)C0.zip',
 'vendor': 'zyxel',
 'version': u'V5.11(AASZ.3)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:29 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=NBG5715&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:29 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2015, 6, 18, 0, 0),
 'product': u'NBG5715',
 'url': u'ftp://ftp2.zyxel.com/NBG5715/firmware/NBG5715_V1.00(AAAG.8)C0.zip',
 'vendor': 'zyxel',
 'version': u'V1.00(AAAG.8)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:29 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2014, 1, 21, 0, 0),
 'product': u'NBG5715',
 'url': u'ftp://ftp2.zyxel.com/NBG5715/firmware/NBG5715_1.00(AAAG.7)C0.zip',
 'vendor': 'zyxel',
 'version': u'1.00(AAAG.7)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:29 [scrapy.core.scraper] ERROR: Error processing {'date': datetime.datetime(2013, 5, 15, 0, 0),
 'product': u'NBG5715',
 'url': u'ftp://ftp2.zyxel.com/NBG5715/firmware/NBG5715_1.00(AAAG.5)C0.zip',
 'vendor': 'zyxel',
 'version': u'1.00(AAAG.5)C0'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 79, in process_item
    requests = arg_to_iter(self.get_media_requests(item, info))
  File "/root/firmadyne/sources/scraper/firmware/pipelines.py", line 78, in get_media_requests
    for x in ["mib", "url"] if x in item]
  File "/usr/local/lib/python2.7/dist-packages/scrapy/item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'FirmwareImage does not support field: None'
2017-11-18 21:46:30 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.zyxel.com/us/en/support/SearchResultTab.shtml?c=us&l=en&t=dl&md=NWD2705&mt=Firmware&mt=MIBFile> (referer: http://www.zyxel.com/us/en/support/download_landing.shtml)
2017-11-18 21:46:30 [scrapy.core.engine] INFO: Closing spider (finished)
2017-11-18 21:46:30 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 340742,
 'downloader/request_count': 878,
 'downloader/request_method_count/GET': 878,
 'downloader/response_bytes': 2485303,
 'downloader/response_count': 878,
 'downloader/response_status_count/200': 878,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 11, 19, 5, 46, 30, 279406),
 'item_dropped_count': 2,
 'item_dropped_reasons_count/DropItem': 2,
 'log_count/DEBUG': 879,
 'log_count/ERROR': 976,
 'log_count/INFO': 16,
 'log_count/WARNING': 2,
 'memusage/max': 37892096,
 'memusage/startup': 29310976,
 'request_depth_max': 1,
 'response_received_count': 878,
 'scheduler/dequeued': 878,
 'scheduler/dequeued/memory': 878,
 'scheduler/enqueued': 878,
 'scheduler/enqueued/memory': 878,
 'start_time': datetime.datetime(2017, 11, 19, 5, 37, 6, 979585)}
2017-11-18 21:46:30 [scrapy.core.engine] INFO: Spider closed (finished)

I don't know what's the problem.

**Comment by ddcc** [comment]
Pull the latest version of the scraper. I just updated the submodule version.

**Comment by yuanchang200** [comment]
Oh I think it works now, thank you very much. Also, I saw in your paper that you analyze more than 9000 firmware, can I ask how did you run these firmware automatically?

**Comment by ddcc** [comment]
We just iterated through the firmware sequentially from the database with a script.

**Comment by yuanchang200** [comment]
I see. Thank you very much.
