### ISSUE TITLE
Error when running scrapy

### ISSUE THREAD

**Issue by allRiceOnMe** [firmadyne/scraper#2]
When I try to run `scrapy crawl dlink` (out of scraper directory) I'm getting following error:

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/**init**.py", line 108, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named firmware.settings

Do you know what could cause this? Thanks!

**Comment by ddcc** [comment]
Are you using the latest version of the `scraper` repository? There were some bugs fixed a while back, but the current version should work.

**Comment by allRiceOnMe** [comment]
You're right. Thanks a lot!
