### ISSUE TITLE
Database schema missing

### ISSUE THREAD

**Issue by fantostisch** [firmadyne/scraper#27]
After creating a database `firmware` with user `firmadyne`, using `SQL_SERVER = "127.0.0.1"` in settings.py and running, the following errors occur:
```
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.9/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/xx/xx/scraper/firmware/pipelines.py", line 99, in item_completed
    cur.execute("SELECT id FROM image WHERE hash=%s",
psycopg2.errors.UndefinedTable: relation "image" does not exist
LINE 1: SELECT id FROM image WHERE hash='efbe8afe54100787cc53157d698...
                       ^

2022-02-11 23:18:58 [firmware.pipelines] WARNING: Database connection exception: relation "image" does not exist
LINE 1: SELECT id FROM image WHERE hash='a3bc15e95e865e08a9d0ad6be62...
                       ^
```

This is probably caused by my database not having any tables. Unfortunately, I can not find how to initialize the database.  If someone has the database running the schema can be exported using:
```bash
sudo su - postgres
pg_dump -s firmware
```

**Comment by ddcc** [comment]
https://github.com/firmadyne/firmadyne#database

**Comment by fantostisch** [comment]
Thanks!
