### ISSUE TITLE
[boto] ERROR: Unable to read instance data, giving up

### ISSUE THREAD

**Issue by nimrodpar** [firmadyne/scraper#7]
Hi,

I installed the deps and removed the SQL line in settings, and i get this (and it just stalls) when running `scrapy crawl dlink`:
```
2017-02-07 15:02:03 [boto] DEBUG: Retrieving credentials from metadata server.
2017-02-07 15:02:04 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-02-07 15:02:04 [boto] ERROR: Unable to read instance data, giving up
2017-02-07 15:02:04 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-02-07 15:02:04 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
```

What am i doing wrong?

Thanks!

**Comment by ddcc** [comment]
Looks like a [scrapy bug](https://github.com/scrapy/scrapy/issues/1054), either upgrade to scrapy 1.x or add `DOWNLOAD_HANDLERS = {'s3': None}` to `settings.py`

**Comment by nimrodpar** [comment]
Thanks, i added that and there's no error indeed, but still it just stalls and nothing happens (it's been running for hours now). Any advice?

**Comment by ddcc** [comment]
What's the output of scrapy with the verbose flag (`-v`)?

**Comment by nimrodpar** [comment]
Indeed it was a `scrapy` issue (i thought `apt-get` gets the latest version but it didn't and later had conflicts), removed everything and got the latest scrapy from pip and it works. Thanks for your help.

**Comment by athulaugustine** [comment]
Did you fix it. I have the same issue

**Comment by ddcc** [comment]
It's a scrapy bug. Did you install the latest version using pip?

**Comment by athulaugustine** [comment]
How to install the latest version ?? I did the normal installation procedure. Can you please give me your contact details , anyway I can reach you ?

**Comment by ddcc** [comment]
Did you follow the instructions on the [scrapy](https://scrapy.org/) website to install it using pip? That currently install scrapy 1.5.0, which has fixed this bug.

**Comment by athulaugustine** [comment]
I have the latest version.
