### ISSUE TITLE
Scrapy Hangs

### ISSUE THREAD

**Issue by ksbickmore** [firmadyne/scraper#8]
After the following scrapy command and errors. Nothing else seems to happen and the scraper just hangs forever.  I'm not sure what I'm missing to make this work.  This is being run from an Ubuntu 16.04 VM.

scrapy crawl dlink
2017-03-21 17:11:51 [scrapy] INFO: Scrapy 1.0.3 started (bot: firmware)
2017-03-21 17:11:51 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-03-21 17:11:51 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'scraper.spiders', 'DOWNLOAD_TIMEOUT': 1200, 'CONCURRENT_REQUESTS': 8, 'DOWNLOAD_WARNSIZE': 0, 'SPIDER_MODULES': ['firmware.spiders'], 'BOT_NAME': 'firmware', 'DOWNLOAD_MAXSIZE': 0, 'USER_AGENT': 'FirmwareBot/1.0 (+https://github.com/firmadyne/scraper)'}
2017-03-21 17:11:51 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState, AutoThrottle
2017-03-21 17:11:51 [boto] DEBUG: Retrieving credentials from metadata server.
2017-03-21 17:11:52 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url   r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open raise URLError(err)
URLError: <urlopen error timed out>
2017-03-21 17:11:52 [boto] ERROR: Unable to read instance data, giving up
2017-03-21 17:11:52 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-03-21 17:11:52 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware

**Comment by ddcc** [comment]
Duplicate, see #7
